# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e838e84c7c5a6ec158c3aa98417c938b49fe5d124d13c5e9e7c51d909521004dbdbba43a05641baf862176e43e041bb573c172bbd4c486121e3fa7b39c1dfab

test:
  secret_key_base: 898442f6256bd8bebee1fb813b125c5050f98c97bc2177d10e4bba539289d80c75949f3eb5552b33dcc031bbe3793a10cb1482254b66b4692a67120c36c593cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
